# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install and build
        run: |
          npm install --legacy-peer-deps
          npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: webpack artifacts
          path: public/
        
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: webpack artifacts
          path: public
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install and test
        run: |
          npm install --legacy-peer-deps
          npm test
        env:
          CI: true
